version: "2"

services:
  jenkins:
    image: jenkins
    ports:
      - "80:8080"
    links:
      - slave
    networks:
      - front-tier
      - back-tier
  slave:
    image: otomato/jenkins-slave:0.5
    volumes:
      - ~/.kube/config:/home/jenkins/.kube/config
    networks:
      - front-tier
      - back-tier

networks:
  front-tier:
  back-tier:
