version: "2"

services:
  jenkins:
    image: jenkins
    ports:
      - "80:8080"
    links:
      - slave2
    networks:
      - front-tier
      - back-tier
  slave2:
    image: otomato/jenkins-slave:0.3
    networks:
      - front-tier
      - back-tier

networks:
  front-tier:
  back-tier:
