version: "2"

services:
  jenkins:
    image: jenkins
    ports:
      - "80:8080"
    links:
      - slave1
    networks:
      - front-tier
      - back-tier

  slave1:
    image: otomato/jenkins-slave:0.1
    networks:
      - front-tier
      - back-tier

networks:
  front-tier:
  back-tier:
